# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

# Set the version before every lane...
before_all do
    # xcode_select("/Applications/Xcode8.app")
end

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :custom_lane do
    # add actions here: https://docs.fastlane.tools/actions
  end

  desc "development"
	lane :build_dev do |options|
		update_info_plist
		update_code_signing_settings
		increment_version_number
		build_app(
			scheme: "taroDemo",
			workspace: "taroDemo.xcworkspace",
			export_method: "development",
			configuration: "Debug",
			clean: true,
			xcargs: "GCC_PREPROCESSOR_DEFINITIONS='$(inherited) DEBUG=1'",
			export_options: {
				method: "development",
				compileBitcode: false
			}
		)
	end

	desc "release"
	lane :build_release do |options|
		# xcode_select("/Applications/Xcode8.app")
		update_info_plist
		update_code_signing_settings
		increment_version_number
		increment_build_number
		build_app(
			scheme: "com.yu.yuduoduo",
			# clean: true,
			workspace: "taroDemo.xcworkspace",
		)
	end

	desc "test"
    lane :adhoc_build do
	    # 使用 Gym 打包应用
	    build_app(
	      scheme: "com.yu.yuduoduo", # 替换为你的scheme名称
	      workspace: "taroDemo.xcworkspace", # 如果你的项目使用workspace，则填写此处
	      configuration: "Release", # 打包配置
	      export_method: "ad-hoc", # 打包方式为Ad-Hoc
	      output_directory: "./build", # 打包输出目录
	      output_name: "taroDemo.ipa", # 打包输出文件名
	      export_options: {
	    	provisioningProfiles: {
	    	  "com.yu.yuduoduo" => "certs/yuduoduo.mobileprovision" # 描述文件路径
	    	}
	      },
	      cert: "certs/yuduoduo.p12", # 证书路径
	      cert_password: "123456", # 证书密码
	      sigh: {
	    	download_path: "./fastlane/certs" # sigh下载描述文件存放的路径
	      }
	    )
      end
	
end
